name: Frontend Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: SSH and Deploy to GCP VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VM_IP }}
          username: josegarrera
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          script: |
            docker stop fe || true
            docker rm fe || true
            docker pull josegarrera/fe:${{ github.sha }}
            docker run -d --name fe -p 5173:5173 josegarrera/fe:${{ github.sha }}
