name: Commit

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test -- --testPathPattern=unit

      - name: Run Component Tests
        run: npm test -- --testPathPattern=component

      - name: Run Integration Tests
        run: npm test -- --testPathPattern=integration

      - name: Run Contract Verification Tests
        run: npm test -- --testPathPattern=contract

      - name: Run Linter
        run: npm run lint

      - name: Build frontend
        run: npm run build

      - name: Build Docker image
        run: docker build --build-arg VITE_API_URL=http://${{ secrets.UAT_VM_IP }} -t ${{ secrets.DOCKER_USERNAME }}/fe:$GITHUB_SHA .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fe:$GITHUB_SHA
